name: golang-pipeline
on: push
jobs:
  #lint:
  # runs-on: ubuntu-latest
  #steps:
  # - uses: actions/checkout@v3
  #- uses: actions/setup-go@v4
  #- uses: golangci/golangci-lint-action@v3

  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v4

      - name: Run Tests
        run: GOOS=linux GOARCH=amd64 go test -v ./..

    #go test ./..
    #- name: Vet
    #  run: |
    #    go vet ./...

  deploy:
    name: Push Docker image to DockerHub
    #on:push:tags:- 'v*'

    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: 1andreiboyar1/1andreiboyar1/cicd_worflover

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
